bundler_args: --without development
script:
  - RAKE_ENV=ci bundle exec rake validate
  - RAKE_ENV=ci bundle exec rake spec
  - RAKE_ENV=ci bundle exec rake lint
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.5
env:
  - PUPPET_VERSION=3.5.1
  - PUPPET_VERSION=3.6.2
  - PUPPET_VERSION=3.7.5
  - PUPPET_VERSION=3.8.4
