bundler_args: --without development
script:
  - RAKE_ENV=ci bundle exec rake
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.2
env:
  - PUPPET_VERSION=3.5.1
  - PUPPET_VERSION=3.6.2
  - PUPPET_VERSION=3.7.5
